title: thedoritos.log
url: http://thedoritos.github.io
description: Just a reminder for me

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Guardfile', 'vendor']
