title: private void
url: http://blog.tomshero.net
description: /* just a reminder for me */

permalink: /:year/:month/:title.html
paginate: 10
highlighter: pygments

markdown: redcarpet

exclude: ['README.md', 'CNAME', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Guardfile', 'vendor']
