title: private void
url: http://blog.tomshero.net
description: /* just a reminder for me */

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'CNAME', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Guardfile', 'vendor']
